version: "3.2"

services:
{% for server in minecraft_servers %}
{% if server.state != "absent" %}
  {{ server.id }}:
    image: {{ java_image_name if server.type == "java" else bedrock_image_name }}:{{ server.version | default('latest') }}
    restart: unless-stopped
{% if minecraft_default_network is defined %}
    networks:
{% if server.ip is defined %}
      {{ minecraft_default_network }}:
        ipv4_address: {{ server.ip }}
{% else %}
      {{ minecraft_default_network }}: {}
{% endif %}
    cap_add:
      - NET_ADMIN
{% else %}
    ports:
{% if server.port is defined %}
      - "{{ server.port }}:19132/udp"
{% else %}
      - "19132:19132/udp"
{% endif %}
{% endif %}
    secrets:
      - source: properties.{{ properties | json_query('results[?item.id==`'+server.id+'`].stat.checksum') | first }}
        target: /minecraft/server.properties
      - source: {{ "whitelistjava" if server.type == "java" else "whitelistbedrock" }}.{{ whitelistfilejava.stat.checksum if server.type == "java" else whitelistfilebedrock.stat.checksum }}
        target: /minecraft/whitelist.json
    volumes:
      - {{ minecraft_volume_name }}:/minecraft/worlds

{% endif %}
{% endfor -%}

secrets:
{% for propertiesfile in properties.results %}
  properties.{{ propertiesfile.stat.checksum }}:
    file: "server.properties.{{ propertiesfile.item.id }}"
{% endfor %}

  whitelistbedrock.{{ whitelistfilebedrock.stat.checksum }}:
    file: "whitelist-bedrock.json"
  whitelistjava.{{ whitelistfilejava.stat.checksum }}:
    file: "whitelist-java.json"

{% if minecraft_default_network is defined -%}
networks:
  {{ minecraft_default_network }}:
    external: true
    
{% endif -%}
volumes:
  {{ minecraft_volume_name }}:
    external: true
