- name: Install Docker installation reqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: true

- name: Install Docker's official apt key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} test
    state: present
    filename: docker

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Download Docker Compose
  uri:
    url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    creates: /usr/local/bin/docker-compose

- name: Make Docker Compose executable
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
